INSERT INTO bairro (nome) VALUES ('Azulville 2');
INSERT INTO bairro (nome) VALUES ('Azulville I');
INSERT INTO bairro (nome) VALUES ('Capitão Antas');
INSERT INTO bairro (nome) VALUES ('Ceat');
INSERT INTO bairro (nome) VALUES ('Centreville');
INSERT INTO bairro (nome) VALUES ('Centro');
INSERT INTO bairro (nome) VALUES ('Chácara Flores');
INSERT INTO bairro (nome) VALUES ('Chácara Parque Club');
INSERT INTO bairro (nome) VALUES ('Chácara São João');
INSERT INTO bairro (nome) VALUES ('Cidade Aracy');
INSERT INTO bairro (nome) VALUES ('Cidade Aracy II');
INSERT INTO bairro (nome) VALUES ('Cidade Jardim');
INSERT INTO bairro (nome) VALUES ('Condomínio Parque Residencial Damha Ll');
INSERT INTO bairro (nome) VALUES ('Conjunto Habitacional Arnon Mello');
INSERT INTO bairro (nome) VALUES ('Conjunto Habitacional Dom C Amstalden');
INSERT INTO bairro (nome) VALUES ('Conjunto Habitacional Dom Conselheiro');
INSERT INTO bairro (nome) VALUES ('Conjunto Habitacional Planalto Verde');
INSERT INTO bairro (nome) VALUES ('Conjunto Habitacional Santa An');
INSERT INTO bairro (nome) VALUES ('Conjunto Habitacional Santa Angelina');
INSERT INTO bairro (nome) VALUES ('Conjunto Habitacional São Carlos Ii');
INSERT INTO bairro (nome) VALUES ('Conjunto Habitacional São Carlos Iii');
INSERT INTO bairro (nome) VALUES ('Conjunto Habitacional São Carlos Vi');
INSERT INTO bairro (nome) VALUES ('Conjunto Habitacional São Carlos Vila');
INSERT INTO bairro (nome) VALUES ('Conjunto Habitacional Waldomiro Lobbe Sobº');
INSERT INTO bairro (nome) VALUES ('Coop Habitacional Bicão');
INSERT INTO bairro (nome) VALUES ('Distrito Ind Miguel Adbelnur');
INSERT INTO bairro (nome) VALUES ('Distrito Indusrial');
INSERT INTO bairro (nome) VALUES ('Distrito Industrial Área Tecnologia');
INSERT INTO bairro (nome) VALUES ('Jardim Acapulco');
INSERT INTO bairro (nome) VALUES ('Jardim Alvorada');
INSERT INTO bairro (nome) VALUES ('Jardim Bandeirantes');
INSERT INTO bairro (nome) VALUES ('Jardim Beatriz');
INSERT INTO bairro (nome) VALUES ('Jardim Bethânia');
INSERT INTO bairro (nome) VALUES ('Jardim Bicão');
INSERT INTO bairro (nome) VALUES ('Jardim Botafogo');
INSERT INTO bairro (nome) VALUES ('Jardim Botafogo 1');
INSERT INTO bairro (nome) VALUES ('Jardim Brasil');
INSERT INTO bairro (nome) VALUES ('Jardim Cardinalli');
INSERT INTO bairro (nome) VALUES ('Jardim Centenário');
INSERT INTO bairro (nome) VALUES ('Jardim Coqueiros');
INSERT INTO bairro (nome) VALUES ('Jardim Cruzeiro do Sul');
INSERT INTO bairro (nome) VALUES ('Jardim Cruzeiro Sul');
INSERT INTO bairro (nome) VALUES ('Jardim das Torres');
INSERT INTO bairro (nome) VALUES ('Jardim de Cresci');
INSERT INTO bairro (nome) VALUES ('Jardim Dona Francisca');
INSERT INTO bairro (nome) VALUES ('Jardim dos Coqueiros');
INSERT INTO bairro (nome) VALUES ('Jardim Embaré');
INSERT INTO bairro (nome) VALUES ('Jardim Gibertoni');
INSERT INTO bairro (nome) VALUES ('Jardim Gonzaga');
INSERT INTO bairro (nome) VALUES ('Jardim Guanabara');
INSERT INTO bairro (nome) VALUES ('Jardim Hikare');
INSERT INTO bairro (nome) VALUES ('Jardim Ipanema');
INSERT INTO bairro (nome) VALUES ('Jardim Itamarati');
INSERT INTO bairro (nome) VALUES ('Jardim Jockei Club Área');
INSERT INTO bairro (nome) VALUES ('Jardim Lutfalla');
INSERT INTO bairro (nome) VALUES ('Jardim Macarengo');
INSERT INTO bairro (nome) VALUES ('Jardim Maracanã');
INSERT INTO bairro (nome) VALUES ('Jardim Maria Alice');
INSERT INTO bairro (nome) VALUES ('Jardim Medeiros');
INSERT INTO bairro (nome) VALUES ('Jardim Mercedes');
INSERT INTO bairro (nome) VALUES ('Jardim Mirante B Vista');
INSERT INTO bairro (nome) VALUES ('Jardim Monique');
INSERT INTO bairro (nome) VALUES ('Jardim Monique II');
INSERT INTO bairro (nome) VALUES ('Jardim Munique');
INSERT INTO bairro (nome) VALUES ('Jardim Nossa Senhora Aparecida');
INSERT INTO bairro (nome) VALUES ('Jardim Nova Santa Paula');
INSERT INTO bairro (nome) VALUES ('Jardim Nova São Carlos');
INSERT INTO bairro (nome) VALUES ('Jardim Novo Horizonte');
INSERT INTO bairro (nome) VALUES ('Jardim Pacaembu');
INSERT INTO bairro (nome) VALUES ('Jardim Paraíso');
INSERT INTO bairro (nome) VALUES ('Jardim Paulista');
INSERT INTO bairro (nome) VALUES ('Jardim Paulistano');
INSERT INTO bairro (nome) VALUES ('Jardim Real');
INSERT INTO bairro (nome) VALUES ('Jardim Ricetti');
INSERT INTO bairro (nome) VALUES ('Jardim Santa Elisa');
INSERT INTO bairro (nome) VALUES ('Jardim Santa Felícia');
INSERT INTO bairro (nome) VALUES ('Jardim Santa Helena');
INSERT INTO bairro (nome) VALUES ('Jardim Santa Maria II');
INSERT INTO bairro (nome) VALUES ('Jardim Santa Paula');
INSERT INTO bairro (nome) VALUES ('Jardim Santa Tereza');
INSERT INTO bairro (nome) VALUES ('Jardim São Carlos');
INSERT INTO bairro (nome) VALUES ('Jardim São Carlos 5');
INSERT INTO bairro (nome) VALUES ('Jardim São João Batista');
INSERT INTO bairro (nome) VALUES ('Jardim São Paulo');
INSERT INTO bairro (nome) VALUES ('Jardim São Rafael');
INSERT INTO bairro (nome) VALUES ('Jardim Social Belvedere');
INSERT INTO bairro (nome) VALUES ('Jardim Social Bicão');
INSERT INTO bairro (nome) VALUES ('Jardim Social Presidente Collo');
INSERT INTO bairro (nome) VALUES ('Jardim Social Presidente Collor');
INSERT INTO bairro (nome) VALUES ('Jardim Tangará');
INSERT INTO bairro (nome) VALUES ('Jardim Tijuca');
INSERT INTO bairro (nome) VALUES ('Jardim Torres');
INSERT INTO bairro (nome) VALUES ('Jardim Veneza');
INSERT INTO bairro (nome) VALUES ('Loteamento Albertini');
INSERT INTO bairro (nome) VALUES ('Loteamento Arace de Santo Antônio I');
INSERT INTO bairro (nome) VALUES ('Loteamento Habitacional São Carlos 1');
INSERT INTO bairro (nome) VALUES ('Loteamento Habitacional São Carlos 2');
INSERT INTO bairro (nome) VALUES ('Loteamento Municipal São Carlos 3');
INSERT INTO bairro (nome) VALUES ('Loteamento Municipal São Carlos 4');
INSERT INTO bairro (nome) VALUES ('Loteamento Município São Carlos 3');
INSERT INTO bairro (nome) VALUES ('Loteamento São Carlos Club');
INSERT INTO bairro (nome) VALUES ('Loteamento Social Antenor Garc');
INSERT INTO bairro (nome) VALUES ('Loteamento Social Antenor Garcia');
INSERT INTO bairro (nome) VALUES ('Loteamento Tutoya do Vale');
INSERT INTO bairro (nome) VALUES ('Mirante da Bela Vista');
INSERT INTO bairro (nome) VALUES ('Morada dos Deuses');
INSERT INTO bairro (nome) VALUES ('Núcleo Residencial Castelo Branco');
INSERT INTO bairro (nome) VALUES ('Núcleo Residencial Sílvio Vilari');
INSERT INTO bairro (nome) VALUES ('Parque Arnold Schimidt');
INSERT INTO bairro (nome) VALUES ('Parque Belvedere');
INSERT INTO bairro (nome) VALUES ('Parque Delta');
INSERT INTO bairro (nome) VALUES ('Parque dos Timburis');
INSERT INTO bairro (nome) VALUES ('Parque Faber');
INSERT INTO bairro (nome) VALUES ('Parque Faber Castell I');
INSERT INTO bairro (nome) VALUES ('Parque Faber Castell Ii');
INSERT INTO bairro (nome) VALUES ('Parque Feher');
INSERT INTO bairro (nome) VALUES ('Parque Fehr');
INSERT INTO bairro (nome) VALUES ('Parque Itaipu');
INSERT INTO bairro (nome) VALUES ('Parque Novo Mundo');
INSERT INTO bairro (nome) VALUES ('Parque Paraíso');
INSERT INTO bairro (nome) VALUES ('Parque Primavera');
INSERT INTO bairro (nome) VALUES ('Parque Residencial Maria Stella Faga');
INSERT INTO bairro (nome) VALUES ('Parque Sabará');
INSERT INTO bairro (nome) VALUES ('Parque Santa Felícia Jardim');
INSERT INTO bairro (nome) VALUES ('Parque Santa Marta');
INSERT INTO bairro (nome) VALUES ('Parque Santa Mônica');
INSERT INTO bairro (nome) VALUES ('Parque São José');
INSERT INTO bairro (nome) VALUES ('Parque Sisi');
INSERT INTO bairro (nome) VALUES ('Parque T D I São Carlos');
INSERT INTO bairro (nome) VALUES ('Planalto Paraíso');
INSERT INTO bairro (nome) VALUES ('Portal do Sol');
INSERT INTO bairro (nome) VALUES ('Portal Sol');
INSERT INTO bairro (nome) VALUES ('Quinta dos Buritis');
INSERT INTO bairro (nome) VALUES ('Recanto Bandeirantes II');
INSERT INTO bairro (nome) VALUES ('Recreio dos Bandeirantes');
INSERT INTO bairro (nome) VALUES ('Recreio São Judas Tadeu');
INSERT INTO bairro (nome) VALUES ('Residencial Américo Alves Margarido');
INSERT INTO bairro (nome) VALUES ('Residencial Américo Area Margarido');
INSERT INTO bairro (nome) VALUES ('Residencial Astolpho Luiz do');
INSERT INTO bairro (nome) VALUES ('Residencial Astolpho Luiz do Prado');
INSERT INTO bairro (nome) VALUES ('Residencial Astolpho Luiz Prado');
INSERT INTO bairro (nome) VALUES ('Residencial Castelo Branco');
INSERT INTO bairro (nome) VALUES ('Residencial Deputado José Zava');
INSERT INTO bairro (nome) VALUES ('Residencial Deputado José Zavaglia');
INSERT INTO bairro (nome) VALUES ('Residencial Eldorado');
INSERT INTO bairro (nome) VALUES ('Residencial Itamarati');
INSERT INTO bairro (nome) VALUES ('Residencial Monsenhor Romeu Tortorelli');
INSERT INTO bairro (nome) VALUES ('Residencial Parati');
INSERT INTO bairro (nome) VALUES ('Residencial Parque Douradinho');
INSERT INTO bairro (nome) VALUES ('Residencial Samambaia');
INSERT INTO bairro (nome) VALUES ('Residencial Tecumseh Village');
INSERT INTO bairro (nome) VALUES ('Romeu Santini');
INSERT INTO bairro (nome) VALUES ('Santa Angleia');
INSERT INTO bairro (nome) VALUES ('Santa Felicidade');
INSERT INTO bairro (nome) VALUES ('São Carlos Viii');
INSERT INTO bairro (nome) VALUES ('Vale Santa Felicidade');
INSERT INTO bairro (nome) VALUES ('Vila Alpes');
INSERT INTO bairro (nome) VALUES ('Vila Arnaldo');
INSERT INTO bairro (nome) VALUES ('Vila Bela Vista');
INSERT INTO bairro (nome) VALUES ('Vila Boa Vista');
INSERT INTO bairro (nome) VALUES ('Vila Boa Vista 1');
INSERT INTO bairro (nome) VALUES ('Vila Brasília');
INSERT INTO bairro (nome) VALUES ('Vila Carmem');
INSERT INTO bairro (nome) VALUES ('Vila Celina');
INSERT INTO bairro (nome) VALUES ('Vila Conceição');
INSERT INTO bairro (nome) VALUES ('Vila Costa do Sol');
INSERT INTO bairro (nome) VALUES ('Vila Costa Sol');
INSERT INTO bairro (nome) VALUES ('Vila Deriggi');
INSERT INTO bairro (nome) VALUES ('Vila Elizabeth');
INSERT INTO bairro (nome) VALUES ('Vila Faria');
INSERT INTO bairro (nome) VALUES ('Vila Irene');
INSERT INTO bairro (nome) VALUES ('Vila Izabel');
INSERT INTO bairro (nome) VALUES ('Vila Jacobucci');
INSERT INTO bairro (nome) VALUES ('Vila Lutfalla');
INSERT INTO bairro (nome) VALUES ('Vila Marcelino');
INSERT INTO bairro (nome) VALUES ('Vila Marina');
INSERT INTO bairro (nome) VALUES ('Vila Monte Carlo');
INSERT INTO bairro (nome) VALUES ('Vila Monteiro');
INSERT INTO bairro (nome) VALUES ('Vila Morumbi');
INSERT INTO bairro (nome) VALUES ('Vila Nery');
INSERT INTO bairro (nome) VALUES ('Vila Nossa Senhora de Fátima');
INSERT INTO bairro (nome) VALUES ('Vila Nossa Senhora Fátima');
INSERT INTO bairro (nome) VALUES ('Vila Pelicano');
INSERT INTO bairro (nome) VALUES ('Vila Prado');
INSERT INTO bairro (nome) VALUES ('Vila Pureza');
INSERT INTO bairro (nome) VALUES ('Vila Rancho Velho');
INSERT INTO bairro (nome) VALUES ('Vila Santa-Madre Cabrini');
INSERT INTO bairro (nome) VALUES ('Vila São José');
INSERT INTO bairro (nome) VALUES ('Vila Sônia');
INSERT INTO bairro (nome) VALUES ('Vila Vista Alegre');
