select insertbairro('Azulville 2');
select insertbairro('Azulville I');
select insertbairro('Capitão Antas');
select insertbairro('Ceat');
select insertbairro('Centreville');
select insertbairro('Centro');
select insertbairro('Chácara Flores');
select insertbairro('Chácara Parque Club');
select insertbairro('Chácara São João');
select insertbairro('Cidade Aracy');
select insertbairro('Cidade Aracy II');
select insertbairro('Cidade Jardim');
select insertbairro('Condomínio Parque Residencial Damha Ll');
select insertbairro('Conjunto Habitacional Arnon Mello');
select insertbairro('Conjunto Habitacional Dom C Amstalden');
select insertbairro('Conjunto Habitacional Dom Conselheiro');
select insertbairro('Conjunto Habitacional Planalto Verde');
select insertbairro('Conjunto Habitacional Santa An');
select insertbairro('Conjunto Habitacional Santa Angelina');
select insertbairro('Conjunto Habitacional São Carlos Ii');
select insertbairro('Conjunto Habitacional São Carlos Iii');
select insertbairro('Conjunto Habitacional São Carlos Vi');
select insertbairro('Conjunto Habitacional São Carlos Vila');
select insertbairro('Conjunto Habitacional Waldomiro Lobbe Sobº');
select insertbairro('Coop Habitacional Bicão');
select insertbairro('Distrito Ind Miguel Adbelnur');
select insertbairro('Distrito Indusrial');
select insertbairro('Distrito Industrial Área Tecnologia');
select insertbairro('Jardim Acapulco');
select insertbairro('Jardim Alvorada');
select insertbairro('Jardim Bandeirantes');
select insertbairro('Jardim Beatriz');
select insertbairro('Jardim Bethânia');
select insertbairro('Jardim Bicão');
select insertbairro('Jardim Botafogo');
select insertbairro('Jardim Botafogo 1');
select insertbairro('Jardim Brasil');
select insertbairro('Jardim Cardinalli');
select insertbairro('Jardim Centenário');
select insertbairro('Jardim Coqueiros');
select insertbairro('Jardim Cruzeiro do Sul');
select insertbairro('Jardim Cruzeiro Sul');
select insertbairro('Jardim das Torres');
select insertbairro('Jardim de Cresci');
select insertbairro('Jardim Dona Francisca');
select insertbairro('Jardim dos Coqueiros');
select insertbairro('Jardim Embaré');
select insertbairro('Jardim Gibertoni');
select insertbairro('Jardim Gonzaga');
select insertbairro('Jardim Guanabara');
select insertbairro('Jardim Hikare');
select insertbairro('Jardim Ipanema');
select insertbairro('Jardim Itamarati');
select insertbairro('Jardim Jockei Club Área');
select insertbairro('Jardim Lutfalla');
select insertbairro('Jardim Macarengo');
select insertbairro('Jardim Maracanã');
select insertbairro('Jardim Maria Alice');
select insertbairro('Jardim Medeiros');
select insertbairro('Jardim Mercedes');
select insertbairro('Jardim Mirante B Vista');
select insertbairro('Jardim Monique');
select insertbairro('Jardim Monique II');
select insertbairro('Jardim Munique');
select insertbairro('Jardim Nossa Senhora Aparecida');
select insertbairro('Jardim Nova Santa Paula');
select insertbairro('Jardim Nova São Carlos');
select insertbairro('Jardim Novo Horizonte');
select insertbairro('Jardim Pacaembu');
select insertbairro('Jardim Paraíso');
select insertbairro('Jardim Paulista');
select insertbairro('Jardim Paulistano');
select insertbairro('Jardim Real');
select insertbairro('Jardim Ricetti');
select insertbairro('Jardim Santa Elisa');
select insertbairro('Jardim Santa Felícia');
select insertbairro('Jardim Santa Helena');
select insertbairro('Jardim Santa Maria II');
select insertbairro('Jardim Santa Paula');
select insertbairro('Jardim Santa Tereza');
select insertbairro('Jardim São Carlos');
select insertbairro('Jardim São Carlos 5');
select insertbairro('Jardim São João Batista');
select insertbairro('Jardim São Paulo');
select insertbairro('Jardim São Rafael');
select insertbairro('Jardim Social Belvedere');
select insertbairro('Jardim Social Bicão');
select insertbairro('Jardim Social Presidente Collo');
select insertbairro('Jardim Social Presidente Collor');
select insertbairro('Jardim Tangará');
select insertbairro('Jardim Tijuca');
select insertbairro('Jardim Torres');
select insertbairro('Jardim Veneza');
select insertbairro('Loteamento Albertini');
select insertbairro('Loteamento Arace de Santo Antônio I');
select insertbairro('Loteamento Habitacional São Carlos 1');
select insertbairro('Loteamento Habitacional São Carlos 2');
select insertbairro('Loteamento Municipal São Carlos 3');
select insertbairro('Loteamento Municipal São Carlos 4');
select insertbairro('Loteamento Município São Carlos 3');
select insertbairro('Loteamento São Carlos Club');
select insertbairro('Loteamento Social Antenor Garc');
select insertbairro('Loteamento Social Antenor Garcia');
select insertbairro('Loteamento Tutoya do Vale');
select insertbairro('Mirante da Bela Vista');
select insertbairro('Morada dos Deuses');
select insertbairro('Núcleo Residencial Castelo Branco');
select insertbairro('Núcleo Residencial Sílvio Vilari');
select insertbairro('Parque Arnold Schimidt');
select insertbairro('Parque Belvedere');
select insertbairro('Parque Delta');
select insertbairro('Parque dos Timburis');
select insertbairro('Parque Faber');
select insertbairro('Parque Faber Castell I');
select insertbairro('Parque Faber Castell Ii');
select insertbairro('Parque Feher');
select insertbairro('Parque Fehr');
select insertbairro('Parque Itaipu');
select insertbairro('Parque Novo Mundo');
select insertbairro('Parque Paraíso');
select insertbairro('Parque Primavera');
select insertbairro('Parque Residencial Maria Stella Faga');
select insertbairro('Parque Sabará');
select insertbairro('Parque Santa Felícia Jardim');
select insertbairro('Parque Santa Marta');
select insertbairro('Parque Santa Mônica');
select insertbairro('Parque São José');
select insertbairro('Parque Sisi');
select insertbairro('Parque T D I São Carlos');
select insertbairro('Planalto Paraíso');
select insertbairro('Portal do Sol');
select insertbairro('Portal Sol');
select insertbairro('Quinta dos Buritis');
select insertbairro('Recanto Bandeirantes II');
select insertbairro('Recreio dos Bandeirantes');
select insertbairro('Recreio São Judas Tadeu');
select insertbairro('Residencial Américo Alves Margarido');
select insertbairro('Residencial Américo Area Margarido');
select insertbairro('Residencial Astolpho Luiz do');
select insertbairro('Residencial Astolpho Luiz do Prado');
select insertbairro('Residencial Astolpho Luiz Prado');
select insertbairro('Residencial Castelo Branco');
select insertbairro('Residencial Deputado José Zava');
select insertbairro('Residencial Deputado José Zavaglia');
select insertbairro('Residencial Eldorado');
select insertbairro('Residencial Itamarati');
select insertbairro('Residencial Monsenhor Romeu Tortorelli');
select insertbairro('Residencial Parati');
select insertbairro('Residencial Parque Douradinho');
select insertbairro('Residencial Samambaia');
select insertbairro('Residencial Tecumseh Village');
select insertbairro('Romeu Santini');
select insertbairro('Santa Angleia');
select insertbairro('Santa Felicidade');
select insertbairro('São Carlos Viii');
select insertbairro('Vale Santa Felicidade');
select insertbairro('Vila Alpes');
select insertbairro('Vila Arnaldo');
select insertbairro('Vila Bela Vista');
select insertbairro('Vila Boa Vista');
select insertbairro('Vila Boa Vista 1');
select insertbairro('Vila Brasília');
select insertbairro('Vila Carmem');
select insertbairro('Vila Celina');
select insertbairro('Vila Conceição');
select insertbairro('Vila Costa do Sol');
select insertbairro('Vila Costa Sol');
select insertbairro('Vila Deriggi');
select insertbairro('Vila Elizabeth');
select insertbairro('Vila Faria');
select insertbairro('Vila Irene');
select insertbairro('Vila Izabel');
select insertbairro('Vila Jacobucci');
select insertbairro('Vila Lutfalla');
select insertbairro('Vila Marcelino');
select insertbairro('Vila Marina');
select insertbairro('Vila Monte Carlo');
select insertbairro('Vila Monteiro');
select insertbairro('Vila Morumbi');
select insertbairro('Vila Nery');
select insertbairro('Vila Nossa Senhora de Fátima');
select insertbairro('Vila Nossa Senhora Fátima');
select insertbairro('Vila Pelicano');
select insertbairro('Vila Prado');
select insertbairro('Vila Pureza');
select insertbairro('Vila Rancho Velho');
select insertbairro('Vila Santa-Madre Cabrini');
select insertbairro('Vila São José');
select insertbairro('Vila Sônia');
select insertbairro('Vila Vista Alegre');
